import { useEffect, useMemo, useState } from 'react'
import './App.css'
import { mockApi, type ApiSnapshot } from './api'
import { charters } from './charters'
import { BBCode, BBEditor } from './bbcode'
import { canApprove, canEditCharter, canManageDivision, canManageNews, canSeeFullDivision, canSeeJudicialRegistries, clearanceLabel } from './permissions'
import { testAccounts } from './seed'
import type { Account, Division, NewsItem, PortalData } from './types'

type Page = 'home'|'division'|'charter'|'transfers'|'sanctions'|'blacklists'|'profiles'|'investigations'|'medals'|'judicial'|'control'|'accounts'
const divisions: Division[]=['USAF','SEAL','NETC','SRT','DIS','GS','MJ']
const icons: Record<string,string>={home:'⌂',division:'◈',charter:'§',transfers:'⇄',sanctions:'⚠',blacklists:'⊘',profiles:'▣',investigations:'◎',medals:'✦',judicial:'◆',control:'⚙',accounts:'◉'}
const routePages: Page[]=['home','transfers','sanctions','blacklists','profiles','investigations','medals','judicial','control','accounts']
const parseHash=():{page:Page;division?:Division|'ARMY'}=>{const parts=location.hash.replace(/^#\/?/,'').split('/').filter(Boolean);if(parts[0]==='division'&&divisions.includes(parts[1] as Division))return{page:'division',division:parts[1] as Division};if(parts[0]==='charter'&&(parts[1]==='ARMY'||divisions.includes(parts[1] as Division)))return{page:'charter',division:parts[1] as Division|'ARMY'};if(routePages.includes(parts[0] as Page))return{page:parts[0] as Page};return{page:'home'}}
const pageHash=(page:Page,division?:Division|'ARMY')=>page==='division'||page==='charter'?`#/${page}/${division||'SEAL'}`:`#/${page}`

export default function App(){
  const [user,setUser]=useState<Account|null>(null); const [data,setData]=useState<ApiSnapshot|null>(null); const [loading,setLoading]=useState(true)
  const initial=parseHash(); const [page,setPage]=useState<Page>(initial.page); const [division,setDivision]=useState<Division>((initial.division||'SEAL') as Division); const [menu,setMenu]=useState(false)
  const [loginOpen,setLoginOpen]=useState(false); const [toast,setToast]=useState('');
  const refresh=async(u=user)=>{setLoading(true);setData(await mockApi.snapshot(u));setLoading(false)}
  useEffect(()=>{mockApi.session().then(u=>{setUser(u);return mockApi.snapshot(u)}).then(d=>{setData(d);setLoading(false)});const onHash=()=>{const route=parseHash();setPage(route.page);if(route.division)setDivision(route.division as Division);setMenu(false)};window.addEventListener('hashchange',onHash);if(!location.hash)history.replaceState(null,'',pageHash(initial.page,initial.division));return()=>window.removeEventListener('hashchange',onHash)},[])
  useEffect(()=>{if(page==='judicial'&&!canSeeJudicialRegistries(user)){setPage('home');history.replaceState(null,'',pageHash('home'))}if((page==='control'||page==='accounts')&&!(user&&(canManageNews(user)||canApprove(user)))){setPage('home');history.replaceState(null,'',pageHash('home'))}},[page,user])
  const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(''),2600)}
  const navigate=(p:Page,d?:Division)=>{const target=d||(p==='charter'?(division as Division):undefined);location.hash=pageHash(p,target);setPage(p);if(d)setDivision(d);setMenu(false);window.scrollTo({top:0,behavior:'smooth'})}
  const login=async(n:string,p:string)=>{const u=await mockApi.login(n,p);setUser(u);setData(await mockApi.snapshot(u));setLoginOpen(false);notify(`Вход выполнен: ${u.nickname}`)}
  const quick=async(id:string)=>{const u=await mockApi.quickLogin(id);setUser(u);setData(await mockApi.snapshot(u));setLoginOpen(false);notify(`${clearanceLabel(u.clearance)} активирован`)}
  const logout=async()=>{await mockApi.logout();setUser(null);setData(await mockApi.snapshot(null));navigate('home');notify('Сеанс завершён')}
  const mutate=async(action:string,target:string,fn:(d:PortalData)=>void)=>{if(!user)return;setData(await mockApi.mutate(user,action,target,fn));notify(action)}
  if(loading||!data)return <div className="boot"><div className="radar"></div><b>SFA COMMAND NETWORK</b><span>Установка защищённого соединения...</span></div>
  const props={user,data,division,navigate,mutate,notify,refresh}
  return <div className="app">
    <aside className={menu?'sidebar open':'sidebar'}><Brand/><nav><Nav active={page==='home'} icon="home" label="Оперативная сводка" onClick={()=>navigate('home')}/><Group title="Подразделения">{divisions.map(d=><div key={d} className="nav-division"><button onClick={()=>navigate('division',d)}><span>{d}</span><small>состав</small></button><button title="Устав" onClick={()=>navigate('charter',d)}>§</button></div>)}</Group><Group title="Реестры"><Nav active={page==='transfers'} icon="transfers" label="Переводы и назначения" onClick={()=>navigate('transfers')}/><Nav active={page==='sanctions'} icon="sanctions" label="Реестр санкций" onClick={()=>navigate('sanctions')}/><Nav active={page==='blacklists'} icon="blacklists" label="Чёрные списки" onClick={()=>navigate('blacklists')}/><Nav active={page==='profiles'} icon="profiles" label="Личные дела" onClick={()=>navigate('profiles')}/><Nav active={page==='investigations'} icon="investigations" label="Расследования" onClick={()=>navigate('investigations')}/><Nav active={page==='medals'} icon="medals" label="Реестр медалей" onClick={()=>navigate('medals')}/>{canSeeJudicialRegistries(user)&&<Nav active={page==='judicial'} icon="judicial" label="Закрытые реестры" onClick={()=>navigate('judicial')}/>}</Group>{user&&(canManageNews(user)||canApprove(user))&&<Group title="Система"><Nav active={page==='control'} icon="control" label="Управление порталом" onClick={()=>navigate('control')}/><Nav active={page==='accounts'} icon="accounts" label="Тестовые аккаунты" onClick={()=>navigate('accounts')}/></Group>}</nav><div className="sidebar-foot"><span className="status-dot"></span><div><b>Система в норме</b><small>Mock API · online</small></div></div></aside>
    <div className="main"><header className="topbar"><button className="hamburger" onClick={()=>setMenu(!menu)}>☰</button><div className="breadcrumbs">SFA / <b>{page==='division'||page==='charter'?division:page.toUpperCase()}</b></div><div className="top-actions"><span className="secure">● SECURE</span>{user?<button className="user-chip" onClick={()=>setLoginOpen(true)}><span>{user.nickname.slice(0,2).toUpperCase()}</span><div><b>{user.nickname}</b><small>{clearanceLabel(user.clearance)}</small></div></button>:<button className="primary" onClick={()=>setLoginOpen(true)}>Войти в систему</button>}</div></header><main>
      {page==='home'&&<Home {...props}/>} {page==='division'&&<DivisionPage {...props}/>} {page==='charter'&&<CharterPage {...props}/>} {page==='transfers'&&<Transfers {...props}/>} {page==='sanctions'&&<Sanctions {...props}/>} {page==='blacklists'&&<Blacklists {...props}/>} {page==='profiles'&&<Profiles {...props}/>} {page==='investigations'&&<Investigations {...props}/>} {page==='medals'&&<Medals {...props}/>} {page==='judicial'&&<Judicial {...props}/>} {page==='control'&&<Control {...props}/>} {page==='accounts'&&<Accounts onQuick={quick}/>} 
    </main></div>{loginOpen&&<LoginModal user={user} onClose={()=>setLoginOpen(false)} onLogin={login} onQuick={quick} onLogout={logout}/>} {toast&&<div className="toast">✓ {toast}</div>}
  </div>
}

function Brand(){return <div className="brand"><div className="seal">SFA</div><div><b>SAN FIERRO</b><span>ARMY COMMAND</span></div></div>}
function Group({title,children}:{title:string,children:React.ReactNode}){return <div className="nav-group"><div className="nav-title">{title}</div>{children}</div>}
function Nav({active,icon,label,onClick}:{active:boolean;icon:string;label:string;onClick:()=>void}){return <button className={active?'nav-item active':'nav-item'} onClick={onClick}><i>{icons[icon]}</i><span>{label}</span></button>}
function Header({eyebrow,title,text,actions}:{eyebrow:string;title:string;text?:string;actions?:React.ReactNode}){return <div className="page-head"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{text&&<p>{text}</p>}</div>{actions&&<div className="head-actions">{actions}</div>}</div>}
function Stat({label,value,sub,tone}:{label:string;value:string|number;sub:string;tone?:string}){return <div className={`stat ${tone||''}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Badge({children,tone}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone||''}`}>{children}</span>}
function Empty({text}:{text:string}){return <div className="empty">◇<b>{text}</b><span>Сведения отсутствуют или ограничены вашим уровнем допуска.</span></div>}

function Home({user,data,notify,refresh,navigate}:{user:Account|null;data:ApiSnapshot;notify:(x:string)=>void;refresh:(u?:Account|null)=>Promise<void>;navigate:(p:Page,d?:Division)=>void}){const sync=async()=>{setTimeout(()=>notify('Сводки VK синхронизированы'),500);await mockApi.syncVk(user);await refresh(user)};return <><section className="hero-home"><div className="hero-overlay"></div><div className="hero-content"><span className="eyebrow light">SAN FIERRO ARMY · FIELD COMMAND NETWORK</span><h1>Командный<br/><em>контур армии</em></h1><p>Закрытая информационная система личного состава, оперативных подразделений и Военного суда. Узел связи: Saint-Louis / Sector 07.</p><div className="hero-actions"><button className="primary" onClick={()=>navigate('profiles')}>[ Открыть личные дела ]</button><button className="ghost" onClick={()=>navigate('charter','ARMY' as Division)}>[ Устав армии ]</button></div></div><div className="hero-coords">NODE SFA-04<br/>37°46′N 122°25′W<br/>CHANNEL 08.15</div></section><div className="content"><div className="stats"><Stat label="ЛИЧНЫЙ СОСТАВ" value={data.members.length} sub="ACTIVE PERSONNEL"/><Stat label="БОЕВЫЕ МОДУЛИ" value="07" sub="FIELD UNITS"/><Stat label="АКТИВНЫЕ САНКЦИИ" value={data.sanctions.filter(s=>s.status==='active').length} sub="DISCIPLINE CONTROL" tone="warn"/><Stat label="СТАТУС КОНТУРА" value="ONLINE" sub="SECURE CHANNEL" tone="ok"/></div><div className="section-row"><div><span className="eyebrow">Оперативный канал // 01</span><h2>Сводки командования</h2></div><button className="secondary" onClick={sync}>↻ Получить сводки VK</button></div><div className="news-grid">{data.news.slice(0,3).map(n=><article className="news-card" key={n.id}><div className="news-img" style={{backgroundImage:`url(${n.image})`}}><Badge tone={n.source==='VK'?'blue':'amber'}>{n.source}</Badge></div><div className="news-body"><small>{n.date} // {n.author}</small><h3>{n.title}</h3><p>{n.excerpt}</p><button>[ Открыть донесение ]</button></div></article>)}</div><div className="split"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Кадровый канал // 03</span><h2>Последние назначения</h2></div><button className="secondary" onClick={()=>navigate('transfers')}>Полный реестр →</button></div>{data.transfers.slice(0,3).map(t=><div className="activity" key={t.id}><span className="avatar">{t.nickname.slice(0,2)}</span><div><b>{t.nickname}</b><p>{t.from} <strong>→</strong> {t.to}</p></div><small>{t.date.split(' ')[0]}</small></div>)}</section><section className="panel alert-panel"><span className="eyebrow">Тактический канал // 08</span><h2>Состояние периметра</h2><div className="readiness"><div className="ring"><b>92%</b></div><ul><li>ВОЗДУШНЫЙ СЕКТОР — <b>НОРМА</b></li><li>МОРСКОЙ СЕКТОР — <b>НОРМА</b></li><li className="warning">СКЛАД МАТЕРИАЛОВ — <b>КОНТРОЛЬ</b></li></ul></div></section></div></div></>}

function DivisionPage({user,data,division,navigate}:{user:Account|null;data:ApiSnapshot;division:Division;navigate:(p:Page,d?:Division)=>void}){const [query,setQuery]=useState('');const [officers,setOfficers]=useState(false);const full=canSeeFullDivision(user,division);let members=data.members.filter(m=>m.division===division&&m.nickname.toLowerCase().includes(query.toLowerCase())&&(!officers||/Лейтенант|Майор|Подполковник|Полковник|Генерал/.test(m.rank)));if(!full&&(division==='SRT'||division==='DIS'))members=[...members].sort((a,b)=>{const ah=/Curator/.test(a.position),bh=/Curator/.test(b.position);return ah===bh?a.nickname.localeCompare(b.nickname):ah?-1:1});return <div className="content"><Header eyebrow="Структура армии" title={division} text={divisionText[division]} actions={<button className="secondary" onClick={()=>navigate('charter',division)}>§ Открыть устав</button>}/><div className="division-banner"><div><span>ACTIVE DIVISION</span><h2>{divisionNames[division]}</h2><p>{members.length} военнослужащих в реестре</p></div><div className="division-code">{division}</div></div>{!full&&<div className="classified-note">◈ Ограниченный режим: должности младшего состава скрыты политикой доступа.</div>}<div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по нику..."/><select value={officers?'OFFICERS':'ALL'} onChange={e=>setOfficers(e.target.value==='OFFICERS')}><option value="ALL">Все звания</option><option value="OFFICERS">Офицерский состав</option></select><span>{members.length} записей</span></div><div className="roster">{members.map((m,i)=><div className="member-card" key={m.nickname+i}><div className="avatar large">{m.nickname.slice(0,2)}</div><div><h3>{m.nickname}</h3><p>{m.rank}</p></div><Badge tone={(division==='SRT'||division==='DIS')&&!full&&!/Curator/.test(m.position)?'dark':'blue'}>{(division==='SRT'||division==='DIS')&&!full&&!/Curator/.test(m.position)?'CLASSIFIED':m.position}</Badge></div>)}</div></div>}
const divisionNames:Record<Division,string>={USAF:'United States Air Force',SEAL:'Sea, Air and Land',NETC:'Naval Education and Training Command',SRT:'Special Reaction Team',DIS:'Department of International Security',GS:'General Staff',MJ:'Military Justice'}
const divisionText:Record<Division,string>={USAF:'Регулярное подразделение и кадровый резерв армии.',SEAL:'Многоцелевая группа морских, воздушных и наземных операций.',NETC:'Учебное командование и подготовка личного состава.',SRT:'Специальная группа быстрого реагирования.',DIS:'Разведывательный и контрразведывательный департамент.',GS:'Командный состав San Fierro Army.',MJ:'Военный суд и надзор за законностью.'}

function CharterPage({user,division}:{user:Account|null;division:Division}){const d=(division as string)==='ARMY'?'ARMY':division;const [editing,setEditing]=useState(false);const [value,setValue]=useState(charters[d]);const can=d==='ARMY'?user?.clearance==='6'||user?.clearance==='7':canEditCharter(user,division);return <div className="content narrow"><Header eyebrow="Нормативная база" title={`Устав ${d}`} text="Актуальная редакция. Пояснения Военного суда раскрываются под соответствующими пунктами." actions={can&&<button className="secondary" onClick={()=>setEditing(!editing)}>{editing?'Закрыть редактор':'✎ Редактировать BBCode'}</button>}/>{editing?<BBEditor value={value} onChange={setValue}/>:<article className="document"><div className="document-meta"><Badge tone="ok">Действующая редакция</Badge><span>Обновлено 28.07.2026</span></div><BBCode value={value}/></article>}</div>}

function Transfers({data}:{data:ApiSnapshot}){const [query,setQuery]=useState('');const [division,setDivision]=useState('ALL');const [ascending,setAscending]=useState(false);const rows=[...data.transfers].filter(t=>`${t.nickname} ${t.actor} ${t.from} ${t.to} ${t.reasonType} ${t.reason}`.toLowerCase().includes(query.toLowerCase())&&(division==='ALL'||`${t.from} ${t.to}`.includes(division))).sort((a,b)=>(ascending?1:-1)*a.date.localeCompare(b.date));return <div className="content"><Header eyebrow="Кадровый реестр" title="Переводы и назначения" text="Единая хронология кадровых решений внутри San Fierro Army."/><DataTools query={query} setQuery={setQuery} division={division} setDivision={setDivision} ascending={ascending} setAscending={setAscending}/><Table headers={['Ник','Кто оформил','Откуда','Куда','Основание','Дата']}>{rows.map(t=><tr key={t.id}><td><b>{t.nickname}</b></td><td><Badge tone={t.actor==='CLASSIFIED'?'dark':''}>{t.actor}</Badge></td><td>{t.from}</td><td>{t.to}</td><td><b>{t.reasonType}</b><small className="cell-note">{t.reason}</small></td><td>{t.date}</td></tr>)}</Table></div>}
function Sanctions({user,data,division,mutate}:{user:Account|null;data:ApiSnapshot;division:Division;mutate:(a:string,t:string,f:(d:PortalData)=>void)=>void}){const [filter,setFilter]=useState('ALL');const rows=data.sanctions.filter(s=>filter==='ALL'||s.division===filter);const add=()=>{if(!user)return;mutate('Добавлена санкция','Demo_Offender',d=>d.sanctions.unshift({id:`s${Date.now()}`,offender:'Demo_Offender',issuer:user.nickname,type:'Предупреждение',reason:'Демонстрационная запись',evidence:'https://example.com',date:new Date().toLocaleDateString('ru-RU'),division:division,status:'active'}))};return <div className="content"><Header eyebrow="Дисциплинарный контроль" title="Реестр санкций" text="Армейские и внутривзводные дисциплинарные взыскания." actions={user&&<button className="primary" onClick={add}>+ Новая санкция</button>}/><div className="tabs">{['ALL','ARMY','SEAL','NETC','SRT','DIS'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><Table headers={['Нарушитель','Выдал','Санкция','Причина','Подразделение','Статус']}>{rows.map(s=><tr key={s.id}><td><b>{s.offender}</b></td><td>{s.division==='DIS'&&!canSeeFullDivision(user,'DIS')?'CLASSIFIED':s.issuer}</td><td>{s.type}</td><td>{s.division==='DIS'&&!canSeeFullDivision(user,'DIS')?'Нарушение внутренних НПА':s.reason}</td><td><Badge>{s.division}</Badge></td><td><Badge tone="warn">{s.status}</Badge></td></tr>)}</Table></div>}
function Blacklists({user,data,mutate}:{user:Account|null;data:ApiSnapshot;mutate:(a:string,t:string,f:(d:PortalData)=>void)=>void}){return <div className="content"><Header eyebrow="Контроль допуска" title="Чёрные списки" text="Реестры ограничений подразделений и армии."/><div className="cards-row">{[1,2,3,4].map(x=><Stat key={x} label={`СТЕПЕНЬ ${x}`} value={data.blacklists.filter(b=>b.degree===x).length} sub={x===4?'Требует решения суда':'Решение руководства'} tone={x===4?'warn':''}/>)}</div><Table headers={['Нарушитель','Внёс','Причина','Степень','Подразделение','Дата']}>{data.blacklists.map(b=><tr key={b.id}><td><b>{b.offender}</b></td><td>{b.division==='SRT'&&!canSeeFullDivision(user,'SRT')?'CLASSIFIED':b.issuer}</td><td>{b.division==='SRT'&&!canSeeFullDivision(user,'SRT')?'Нарушение внутренних НПА':b.reason}</td><td><Badge tone={b.degree===4?'red':'warn'}>{b.degree}</Badge></td><td>{b.division}</td><td>{b.date}</td></tr>)}</Table></div>}

function Profiles({user,data}:{user:Account|null;data:ApiSnapshot}){const [selected,setSelected]=useState(data.profiles[0]);const [query,setQuery]=useState('');const rows=data.profiles.filter(p=>p.nickname.toLowerCase().includes(query.toLowerCase()));return <div className="content"><Header eyebrow="Кадровый архив" title="Личные дела" text="Открытая служебная информация и защищённые разделы по допуску."/><div className="profiles-layout"><aside className="profile-list"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск личного дела..."/>{rows.map(p=><button className={selected?.nickname===p.nickname?'active':''} onClick={()=>setSelected(p)}><span className="avatar">{p.nickname.slice(0,2)}</span><div><b>{p.nickname}</b><small>{p.position}</small></div></button>)}</aside>{selected?<article className="profile-sheet"><div className="profile-cover"><div className="avatar xl">{selected.nickname.slice(0,2)}</div><div><Badge>{selected.division}</Badge><h1>{selected.fullName}</h1><p>{selected.rank} · {selected.position}</p></div></div><div className="info-grid"><Info l="Дата рождения" v={selected.birthDate}/><Info l="Место рождения" v={selected.birthPlace}/><Info l="Гражданство" v={selected.citizenship}/><Info l="Место проживания" v={selected.residence}/></div><Section title="Послужной список"><div className="timeline">{selected.serviceHistory.map(x=><span>{x}</span>)}</div></Section><Section title="Профессиональные навыки"><div className="tags">{selected.skills.map(x=><Badge>{x}</Badge>)}</div></Section><Section title="Автобиография"><p>{selected.biography}</p></Section>{selected.secretSection&&<Section title="Секретная часть · DIS / MJ" secret><BBCode value={selected.secretSection}/></Section>}{selected.topSecretSection&&<Section title="Сверхсекретная часть · MJ" topSecret><BBCode value={selected.topSecretSection}/>{selected.registryFlags?.map(x=><div className="registry-flag">◆ {x}</div>)}</Section>}{user&&user.nickname===selected.nickname&&<button className="secondary wide">Подать заявку на изменение личного дела</button>}</article>:<Empty text="Личное дело не выбрано"/>}</div></div>}
function Info({l,v}:{l:string;v:string}){return <div><span>{l}</span><b>{v}</b></div>}
function Section({title,children,secret,topSecret}:{title:string;children:React.ReactNode;secret?:boolean;topSecret?:boolean}){return <section className={`profile-section ${secret?'secret':''} ${topSecret?'topsecret':''}`}><h3>{title}</h3>{children}</section>}

function Investigations({user,data,mutate}:{user:Account|null;data:ApiSnapshot;mutate:(a:string,t:string,f:(d:PortalData)=>void)=>void}){const [selected,setSelected]=useState(data.investigations[0]);const [edit,setEdit]=useState(false);const [value,setValue]=useState(selected?.content||'');const canCreate=!!user&&(user.clearance.includes('D')||['4B','5A','6','7'].includes(user.clearance));const save=()=>selected&&mutate('Расследование отредактировано',selected.title,d=>{const x=d.investigations.find(i=>i.id===selected.id);if(x)x.content=value});const create=()=>{if(!user)return;const id=`i${Date.now()}`;mutate('Создано расследование','Новое расследование',d=>d.investigations.unshift({id,title:'Новое расследование',author:user.nickname,clearance:'0',summary:'Черновик нового расследования.',content:'[B]Новый материал[/B]\nДобавьте описание и доказательства.',date:new Date().toLocaleDateString('ru-RU'),editors:[]}));setSelected({id,title:'Новое расследование',author:user.nickname,clearance:'0',summary:'Черновик нового расследования.',content:'[B]Новый материал[/B]\nДобавьте описание и доказательства.',date:new Date().toLocaleDateString('ru-RU'),editors:[]});setValue('[B]Новый материал[/B]\nДобавьте описание и доказательства.');setEdit(true)};return <div className="content"><Header eyebrow="Оперативные материалы" title="Расследования" text="Список уже отфильтрован mock API согласно вашему допуску." actions={canCreate&&<button className="primary" onClick={create}>+ Создать расследование</button>}/><div className="investigation-layout"><div className="investigation-list">{data.investigations.map(i=><button className={selected?.id===i.id?'active':''} onClick={()=>{setSelected(i);setValue(i.content);setEdit(false)}}><div><Badge tone={i.clearance==='0'?'ok':i.clearance==='5B'?'red':'dark'}>{clearanceLabel(i.clearance)}</Badge><small>{i.date}</small></div><h3>{i.title}</h3><p>{i.summary}</p><span>Автор: {i.author}</span></button>)}</div>{selected?<article className="document investigation-doc"><div className="document-meta"><div><Badge tone={selected.clearance==='0'?'ok':'red'}>{clearanceLabel(selected.clearance)}</Badge><span>{selected.author}</span></div>{user&&(selected.author===user.nickname||user.clearance==='7')&&<button className="secondary" onClick={()=>setEdit(!edit)}>✎ {edit?'Предпросмотр':'Редактировать'}</button>}</div>{edit?<><BBEditor value={value} onChange={setValue}/><button className="primary wide" onClick={save}>Сохранить изменения</button></>:<BBCode value={value}/>}</article>:<Empty text="Материал не выбран"/>}</div></div>}

function Medals({user,data,mutate}:{user:Account|null;data:ApiSnapshot;mutate:(a:string,t:string,f:(d:PortalData)=>void)=>void}){return <div className="content"><Header eyebrow="Наградная система" title="Реестр медалей" text="Статуты, привилегии и список награждённых военнослужащих."/><div className="medals-grid">{data.medals.map(m=><article className="medal-card"><div className="medal-image"><img src={m.image}/></div><Badge>{m.division}</Badge><h3>{m.name}</h3><p>{m.statute}</p><div className="privilege"><b>Привилегия</b>{m.privilege}</div><div className="recipients"><span>Награждены</span>{m.recipients.map(r=><button>{r}</button>)}</div>{user&&<button className="secondary wide" onClick={()=>mutate('Выдана медаль',m.name,d=>{const x=d.medals.find(x=>x.id===m.id);if(x&&!x.recipients.includes(user.nickname))x.recipients.push(user.nickname)})}>Выдать медаль</button>}</article>)}</div></div>}
function Judicial({user,data}:{user:Account|null;data:ApiSnapshot}){if(!canSeeJudicialRegistries(user)||!data.judicialRegistries)return <div className="content"><Empty text="Маршрут не найден"/></div>;return <div className="content"><Header eyebrow="Military Justice · Top Secret" title="Закрытые судебные реестры" text="Информация существует только в модели данных пользователей судебной ветки."/><div className="classified-hero">TOP SECRET // MJ EYES ONLY</div><Table headers={['Категория','Ник','Кто внёс','Основание','Дата']}>{data.judicialRegistries.map(r=><tr><td><Badge tone="red">{r.type}</Badge></td><td><b>{r.nickname}</b></td><td>{r.actor}</td><td>{r.reason}</td><td>{r.date}</td></tr>)}</Table></div>}

function Control({user,data,mutate,refresh}:{user:Account|null;data:ApiSnapshot;mutate:(a:string,t:string,f:(d:PortalData)=>void)=>void;refresh:(u?:Account|null)=>Promise<void>}){if(!user)return <div/>;const approve=(id:string,status:'approved'|'rejected')=>mutate(status==='approved'?'Заявка одобрена':'Заявка отклонена',id,d=>{const x=d.approvals.find(a=>a.id===id);if(x)x.status=status});const reset=async()=>{await mockApi.reset();location.reload()};return <div className="content"><Header eyebrow="Administration console" title="Управление порталом" text="Доступные модули сформированы из полномочий активного пользователя."/><div className="admin-grid"><section className="panel"><span className="eyebrow">Интеграции</span><h2>Источники данных</h2><div className="integration"><div><b>VK · nb69sl</b><small>Новости сообщества</small></div><Badge tone="ok">ADAPTER READY</Badge></div><div className="integration"><div><b>Google Sheets</b><small>Санкции и ЧС армии</small></div><Badge tone="ok">ADAPTER READY</Badge></div><button className="secondary wide" onClick={async()=>{await mockApi.syncGoogle(user);await refresh(user)}}>Синхронизировать источники</button></section><section className="panel"><span className="eyebrow">Демонстрация</span><h2>Локальная база</h2><p>Все изменения сохраняются в localStorage. Сброс восстановит исходные записи и завершит сеанс.</p><button className="danger wide" onClick={reset}>Сбросить демонстрационные данные</button></section></div><section className="panel approvals"><div className="panel-head"><div><span className="eyebrow">Очередь решений</span><h2>Заявки на одобрение</h2></div><Badge tone="warn">{data.approvals.filter(a=>a.status==='pending').length} ожидают</Badge></div>{data.approvals.length?data.approvals.map(a=><div className="approval"><div><Badge>{a.type}</Badge><h3>{a.target}</h3><p>{a.summary}</p><small>{a.applicant} · {a.date}</small></div><div>{canApprove(user)&&a.status==='pending'?<><button className="primary" onClick={()=>approve(a.id,'approved')}>Одобрить</button><button className="danger" onClick={()=>approve(a.id,'rejected')}>Отклонить</button></>:<Badge tone={a.status==='pending'?'warn':a.status==='approved'?'ok':'red'}>{a.status}</Badge>}</div></div>):<Empty text="Нет доступных заявок"/>}</section>{user.clearance==='7'&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">Audit trail</span><h2>Журнал действий</h2></div></div>{data.audit.map(x=><div className="log"><span>◌</span><div><b>{x.action}</b><p>{x.actor} → {x.target}</p></div><small>{x.date}</small></div>)}</section>}</div>}
function Accounts({onQuick}:{onQuick:(id:string)=>void}){return <div className="content"><Header eyebrow="Демонстрационная среда" title="Тестовые аккаунты" text="Пароли различаются последним символом. Быстрый вход работает только в frontend-прототипе."/><div className="account-grid">{testAccounts.map(a=><article className="account-card"><div><span className="avatar">{a.nickname.slice(0,2)}</span><Badge tone={a.clearance==='7'?'red':a.clearance==='0'?'ok':'dark'}>{a.clearance}</Badge></div><h3>{a.nickname}</h3><p>{a.position}</p><code>{a.password}</code><button className="secondary wide" onClick={()=>onQuick(a.id)}>Войти под аккаунтом</button></article>)}</div></div>}

function LoginModal({user,onClose,onLogin,onQuick,onLogout}:{user:Account|null;onClose:()=>void;onLogin:(n:string,p:string)=>Promise<void>;onQuick:(id:string)=>void;onLogout:()=>void}){const [nick,setNick]=useState('Recruit_Demo');const [pass,setPass]=useState('SFA-demo-A');const [error,setError]=useState('');const submit=async()=>{try{await onLogin(nick,pass)}catch(e){setError((e as Error).message)}};return <div className="modal-bg" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><Brand/>{user?<><div className="current-user"><span className="avatar xl">{user.nickname.slice(0,2)}</span><h2>{user.nickname}</h2><p>{user.position} · {clearanceLabel(user.clearance)}</p></div><button className="danger wide" onClick={onLogout}>Завершить сеанс</button><p className="switch-hint">Или выберите другой тестовый уровень:</p></>:<><h2>Авторизация</h2><p>Введите игровой ник и пароль приглашения.</p><label>Nick_Name<input value={nick} onChange={e=>setNick(e.target.value)}/></label><label>Пароль<input type="password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()}/></label>{error&&<div className="form-error">{error}</div>}<button className="primary wide" onClick={submit}>Войти в защищённый контур</button></>}<details className="quick-login"><summary>Быстрый выбор тестовой роли</summary><div>{testAccounts.map(a=><button onClick={()=>onQuick(a.id)}><b>{a.clearance}</b>{a.nickname}</button>)}</div></details></div></div>}
function DataTools({query,setQuery,division,setDivision,ascending,setAscending}:{query:string;setQuery:(value:string)=>void;division:string;setDivision:(value:string)=>void;ascending:boolean;setAscending:(value:boolean)=>void}){return <div className="toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск по реестру..."/><select value={division} onChange={e=>setDivision(e.target.value)}><option value="ALL">Все подразделения</option><option>USAF</option><option>SEAL</option><option>NETC</option><option>SRT</option><option>DIS</option></select><select value={ascending?'ASC':'DESC'} onChange={e=>setAscending(e.target.value==='ASC')}><option value="DESC">Сначала новые</option><option value="ASC">Сначала старые</option></select></div>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="table-wrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
